"""empty message

Revision ID: 5e7c1125e285
Revises: 
Create Date: 2020-12-15 21:00:00.360719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7c1125e285'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amusement', sa.Integer(), nullable=True),
    sa.Column('joy', sa.Integer(), nullable=True),
    sa.Column('beauty', sa.Integer(), nullable=True),
    sa.Column('relaxation', sa.Integer(), nullable=True),
    sa.Column('sadness', sa.Integer(), nullable=True),
    sa.Column('dreaminess', sa.Integer(), nullable=True),
    sa.Column('triumph', sa.Integer(), nullable=True),
    sa.Column('anxiety', sa.Integer(), nullable=True),
    sa.Column('scariness', sa.Integer(), nullable=True),
    sa.Column('annoyance', sa.Integer(), nullable=True),
    sa.Column('defiance', sa.Integer(), nullable=True),
    sa.Column('feelingpumped', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('displayname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trackname', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('trackurl', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('userprofile')
    op.drop_table('moods')
    op.drop_table('images')
    op.drop_table('artists')
    # ### end Alembic commands ###
