name: Automated Tests

on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt;
      - name: Run Tests
        run: |
          cd /home/runner/work/T3A3/T3A3/src
          python -m unittest discover -s tests -v
